### ISSUE TITLE
Fix `EVM.header` mutation and architecture.

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/py-evm#22]
This issue is seeded from this comment:  https://github.com/pipermerriam/py-evm/pull/21/files#r124833739

### What is wrong

Currently, `EVM.header` is used to anchor the chain to the current HEAD state.

Mutation of this value occurs in the following places:

* `EVM.apply_transaction()`
* `EVM.import_block()`
* `EVM.mine_block()`
* `EVM.configure_header()`

This mutation introduces the potential for us to have two separate actions modify the `EVM.header` property and to end up either overwriting something we should not, or just to have some sort of inconsistency.  This is not ideal.

### How can it be fixed.

Not clear at this time but this is something that should likely be addressed because it has the potential to be very problematic down the road.

**Comment by gsalgado** [comment]
I thought we should be able to avoid storing the header as an instance variable in the EVM and instead just store the number of the head block, but that's not easy because there are too many places where we construct an EVM and later call .get_vm() (which needs the head's header) without having first persisted the head block to the DB, so we'd have nowhere to retrieve the header from.

However, ISTM that in EVM.apply_transaction() we don't need to overwrite .header, and EVM.configure_header() is not actually used anywhere, so we end up with just .mine_block() and .import_block() overwriting .header, which doesn't sound so unreasonable

**Comment by pipermerriam** [comment]
Good stuff.  Nice to see this mutation reduced to block imports and creation.  What do you think about the following idea for removal of the mutation from those two methods.

Instead of overwriting the local header object, what if `mine_block()` and `import_block()` returned new EVM instances?

```python
evm = EVM(....)
head_evm = EVM(...).import_block(block_0).import_block(block_1)

# or using some functional tools to apply an arbitrary number of blocks.
blocks_to_import = [block_0, block_1]
head_evm = toolz.functoolz.pipe(  # http://toolz.readthedocs.io/en/latest/api.html#toolz.functoolz.pipe
    EVM(...), 
    *(operator.methodcaller('import_block', block) for block in blocks_to_import)
)
```

This does have the downside of making the API a bit less intuitive.

```python
evm = EVM(....)
# maybe execute some transactions
evm.apply_transaction(...)
# then mine a block.
evm = evm.mine_block()  # Awkward that you have to overwrite the local variable...
# maybe provide an alternate API
evm.mine_block_in_place()  # not ideal....
```

I'm not convinced this is a good idea but I'm curious if it leads towards one.
